verbose: true
origin: '{{ENV.ORIGIN}}'
secret: '{{ENV.SECRET}}'
redis:
  host: '{{ENV.REDIS_HOST}}'
  port: '{{ENV.REDIS_PORT || 6379}}'
  password: '{{ENV.REDIS_PASSWORD}}'
  prefix: '{{ENV.REDIS_PREFIX || "micro-cache"}}'
plugins:
  hapi-auto-handler:
    _priority: -5
  './plugins/store':
